services:
  postgres:
    image: postgres:16
    container_name: supportdesk-postgres
    environment:
      POSTGRES_DB: supportdesk
      POSTGRES_USER: supportdesk
      POSTGRES_PASSWORD: supportdesk
    ports:
      - "5433:5432"
    volumes:
      - supportdesk_pgdata:/var/lib/postgresql/data

volumes:
  supportdesk_pgdata: