server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/supportdesk
spring.datasource.username=supportdesk
spring.datasource.password=supportdesk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true